# Generated by Django 5.0.6 on 2024-07-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('published_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='hh_info',
            options={'verbose_name': 'HH_info', 'verbose_name_plural': 'HH_infos'},
        ),
    ]
