# Generated by Django 5.0.6 on 2024-07-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhapp', '0006_alter_vacancy_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='area',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, null=True),
        ),
    ]
