# Generated by Django 5.0.6 on 2024-07-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhapp', '0007_vacancy_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='area',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
