# Generated by Django 5.0.6 on 2024-07-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhapp', '0008_alter_vacancy_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='employment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
