# Generated by Django 5.0.6 on 2024-07-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhapp', '0009_vacancy_employment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
