version: '3.9'

networks:
  networkName:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: 
          "python manage.py runserver "
    networks:
      - networkName

# Specify volumes, networks, and other configurations as needed
